src/linux.rs
Referenced in https://github.com/EstebanBorai/local-ip-address/issues/10
This issue was causing the Linux flavor of `local-ip-address` to not compile on Raspberry Pi due to a system value being cast to a `*const i8` as opposed to a `*const u8` in an `unsafe` block. Swapping the one character got it to compile without issue on my Raspberry Pi, and I was back up and running.
=> Fix Issue #10

Cargo.toml
`Windows::Win32::NetworkManagement::IpHelper::{IP_ADAPTER_ADDRESSES_LH, GetAdaptersAddresses}` and others are now behind a new feature (`Win32_NetworkManagement_Ndis`) as of [this commit](https://github.com/microsoft/windows-rs/commit/7f2cd7cddbce30685edf822a1b0e02f0d0153bf5#diff-d1ab09ce83262d4c9e199e263119084ebf1cad945d2856b4fc964e4ecf1de0beR131-R132).
This enables the feature.
=> feat: new feature flag in windows crate

src/linux.rs
Temporary fix to be able to use the library even in case of tun device. See https://github.com/EstebanBorai/local-ip-address/issues/24
=> fix: ignore interface with no link address

src/linux.rs, src/macos.rs
Replaces `libc::malloc` with `std::alloc::alloc` to avoid undefined behavior
on certain systems.
Refer: https://github.com/EstebanBorai/local-ip-address/issues/80
=> fix: replace `libc::malloc` with `std::alloc::alloc`

Cargo.toml, src/windows.rs
I forgot to remove the libc dependency in my previous PR. Anyway this PR removes libc as dependency on windows by using std's allocator and implements wcslen by hand. I also updated the windows-sys dependency because it seems to contain some fixes but nothing really changed except from adding a feature flag.
=> feat: remove dependency on libc on windows platforms

src/lib.rs
OpenBSD can use the same API as MacOS and thus be supported.
I guess FreeBSD can also be added but I do not have a test system for it.
=> feat: OpenBSD support

src/lib.rs
This MR aims to improve handling of unsupported OS by handling error cases in the docstrings, as well as implementing fall-back functions in conditional compilation for unsupported operating systems.
See unhelpful error message in #40 for unsupported OS.
Initial suggestion for this feature mentioned here: https://github.com/EstebanBorai/local-ip-address/pull/85#issuecomment-1312857382.
=> fix: improve error handling for unsupported OS

.cirrus.yml, src/bsd.rs, src/lib.rs
This PR implements CI workflow for FreeBSD using Cirrus CI, as previously discussed.<sup>[[1]](https://github.com/EstebanBorai/local-ip-address/pull/85#issuecomment-1312852325), [[2]](https://github.com/EstebanBorai/local-ip-address/pull/87#issuecomment-1315129507)</sup>
In this PR, I also had to fix an error in correctly obtaining the local IP in BSD.
---
- Dynamically obtain local IP interface name for BSD implementation rather than using hard-coded interface names
- When fixing tests for FreeBSD, I had to modify the `find_ifa` function&mdash;renamed to `find_ifas`&mdash;and the `list_afinet_netifas` function.
- The [nix](https://github.com/nix-rust/nix/) package implements the functionality in this project, though its scope is far greater than the likes of this library.
=> Implement CI workflow for FreeBSD using Cirrus

src/linux.rs
This PR fixes an issue in the Linux implementation where a `while` condition checked if the next item (`ifa_next`) would be null before it consumed the current item (`ifa`). This caused the loop to always skip the last ip address, causing it to be omitted from the list returned by `list_afinet_netifas()`.
=> fix(linux): off by one error caused `list_afinet_netifas` to omit the last ip address

src/bsd.rs, src/lib.rs
BSD local IP address was previously hard coded to look for specific interface names.  This pull request solves this by dynamically looking for the first non-loopback local IP in the interface list, which is required for tests to pass for BSD.
This would also close #82.
While this is probably a pretty good solution, it may not be perfect (see #94).
=> Dynamically obtain local IP for BSD

src/lib.rs, src/linux.rs, src/macos.rs
Reintroduce a dedicated macOS implementation.
=> feat: dedicated macos impl

src/linux.rs
Before using the IP of the first non-loopback interface returned by `RTM_GETADDR`, try to use the IP address of the interface routing external traffic via `RTM_GETROUTE`.
=> feat(linux): use `RTM_GETROUTE` before `RTM_GETADDR`

Cargo.toml, src/linux.rs
Rewrite the Linux version of `list_afinet_netifas()` using netlink requests in pure Rust instead of calling the libc interface `getifaddrs(3)`.  This avoids pointer magic and calling unsafe C code.
See https://github.com/EstebanBorai/local-ip-address/pull/88 and https://github.com/EstebanBorai/local-ip-address/pull/93 for exemplary issues.
Based on #102
=> feat(linux): rewrite list_afinet_netifas 

src/linux.rs
fixes #110 ：This pr tries to solve the problem raised by issue #110 ，all network interface names returned by the list_afinet_netifas() method contained an unexpected '\0', I try to use `CStr` to trim the '\0' of the suffix in this pr.
=> fix: trim Unexpected `\0` in network interface name

examples/show_ip_and_ifs.rs, src/lib.rs, src/linux.rs
Similar to `local_ip()` add `local_ipv6()` to get the local IPv6 address.
Only tested on Linux.
=> Add interface to get local IPv6 address

src/linux.rs
Commit 109ff03d ("feat(linux): rewrite list_afinet_netifas (#103)") used the wrong message types for requests, while using the correct ones for responses.  According to rtnetlink(7) RTM_GETLINK messages use the type ifinfomsg and RTM_GETADDR messages use the type ifaddrmsg.
Fixes: 109ff03d ("feat(linux): rewrite list_afinet_netifas (#103)")
Replaces: #120
=> linux: use correct message types for requests

src/linux.rs
Do not override the name of an interface with a label included in a GETADDR response.  That associated label might be an alias name, which should not override the original name.
Fixes: #126
=> fix(linux): do not override interface name by label

examples/show_ip_and_ifs.rs, src/linux.rs
In reference to  #133. This PR adds access to the broadcast ip. A broadcast ip is only a ipv4 feature which is why there is no ipv6 function. The neli crate provided the broadcast ip directly, so I decided to access that instead of netmask. 
Broadcast ip can now be accessed via `local_broadcast_ip()`.
=> feat(linux): `local_broadcast_ip` function

src/error.rs, src/linux.rs
Fix(linux): can not get local ip address when the network namespace without default route
#135
=> fix(linux): can't get local ip address with libc::ENETUNREACH error

src/unix.rs
local_ip() previously returned mobile IP on iOS platform.
=> fix: is_mobile_data() to support without android

Cargo.toml
This should not change the usage of our library.
cc @LeoBorai
=> build: bump thiserror dep to 2

Cargo.toml
Undo MSRV and Edition 2024 on version `0.x`.
=> fix: undo edition and msrv
